version: '3.7'

services:
  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: 'mysql'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - node-db:/var/lib/mysql
    networks:
      - backend
  
  node-sql:
    image: elu/node-sql
    restart: always
    environment:
      NODE_DB_HOST: db
      NODE_DB_USER: root
      NODE_DB_PASSWORD: password
      NODE_DB_NAME: mysql
    ports:
      - '8088:8088'
    expose:
      - '8088'
    networks:
      - backend    
    depends_on:
      - db
      
  ang6:
    image: elu/nginx
    restart: always
    ports:
      - '80:80'
    expose:
      - '80'
    networks:
      - backend
      - frontend    
    depends_on:
      - node-sql    
     
# Names our volume
volumes:
  node-db:

networks:
  backend:
  frontend:

